version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/XKeysSharp/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "nuget"
    directory: "/XKeysSharpTest/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5